### ISSUE TITLE
JSON parse errors fail silently

### ISSUE THREAD

**Issue by 5ebastianMeier** [5minds/nconfetti#16]
This issue details the problem pretty well:
https://github.com/essential-projects/bootstrapper_node/issues/1

Currently the dir scanner just uses an empty object when a JSON parse error occurs. This leads to misbehavior that can not be identified during bootstrapping with the current implementation.

I would like to suggest not to catch the error, but let it happen without intervention.

**Comment by heikomat** [comment]
@5ebastianMeier @ElRaptorus The try-catch is only arount the `JSON.parse` itself:

https://github.com/5minds/nconfetti/blob/f9eae47cd3a194136b6b06328efcf6f39836c9d3/lib/dir_scanner.js#L15

This means the error will contain *what* went wrong, but not *where*. Instead of just not catching it, i suggest throwing a new Error with an error-message that includes the path to the file that couldn'T be parsed. Something like this:

```JavaScript
try {
  const items = JSON.parse(newContent);
  return items;
} catch (error) {
  throw new Error(`couldn't parse package.json at '${filename}': ${parseError.message}`);
}
```

**Comment by 5ebastianMeier** [comment]
The symptoms by which this occured was that for the erroneous configuration parts there was an empty JSON object where the error occured.

**Comment by heikomat** [comment]
@5ebastianMeier i know, that's because the catch there doesn't throw an error, but just returns an empty object.

And i suggest to not return an empty object, but to also not "not catch"-it, but to throw an error that has more information than the error would've if we were to not catch it.

**Comment by ElRaptorus** [comment]
I agree with @heikomat. This way, we would immediately see which config file caused the problem, which is very helpful, if you have loads of files to manage.

**Comment by 5ebastianMeier** [comment]
@heikomat sorry, I was in the middle of something and didn't realize there was an empty object return in the catch. You're absolutely right!
